### ISSUE TITLE
Mention `-F` option to ssh instead of advising to move config around

### ISSUE THREAD

**Issue by klieret** [PrincetonUniversity/removing_tedium#5]
https://github.com/PrincetonUniversity/removing_tedium/blob/6ef8ff6e564ae59574afa2346f968b17d3cac641/01_suppressing_duo/README.md?plain=1#L328

I think this would be easier with just `ssh -F /dev/null` (no config) or `ssh -F path/to/alternate/config`

**Comment by jdh4** [comment]
The page has been updated with these suggestions.
